name: windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: master

    - name: Compile
      run: zig build test

    - run: echo $WORKSPACE/zig-cache/bin >> $GITHUB_PATH
      env:
        WORKSPACE: ${{ GITHUB_WORKSPACE }}

    - name: Search
      run: ./zig-cache/bin/zkg search

    - name: Add
      run: ./zig-cache/bin/zkg add bearssl

    - name: Fetch
      run: ./zig-cache/bin/zkg fetch
