name: windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.5
      with:
        version: 0.7.1

    - run: echo $(pwd)/zig-cache/bin >> $GITHUB_PATH

    - name: Compile
      run: zig build

    - name: Search
      run: zkg search

    - name: Add
      run: zkg add bearssl

    - name: Fetch
      run: zkg fetch

    - name: Example Project
      working-directory: ./tests/example
      run: |
        zkg fetch
        cat deps.zig
        zig build
