name: windows
on:
  push:
    branches: [ master, gyro ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - run: echo $(pwd)/zig-cache/bin >> $GITHUB_PATH

    - name: Bootstrap build
      run: zig build -Dbootstrap

    - run: mkdir tmp
    - name: Self-hosted build
      run: gyro build --prefix tmp
