name: windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - run: echo $(pwd)/zig-out/bin >> $GITHUB_PATH

    - name: Bootstrap build
      run: zig build test -Dbootstrap

    - name: Bootstrap build 32-bit
      run: zig build -Dtarget=i386-windows-gnu --prefix tmp

    - name: Self-hosted build
      run: gyro build test --prefix tmp
